const INCORRECT_INPUT_PATH = 'INCORRECT_INPUT_PATH';
const INCORRECT_OUTPUT_PATH = 'INCORRECT_OUTPUT_PATH';
const ERROR_OCCUR_WHILE_GENERATING_OUTPUT_FILE = 'An error occur while generating output file';

export {
    INCORRECT_INPUT_PATH,
    INCORRECT_OUTPUT_PATH,
    ERROR_OCCUR_WHILE_GENERATING_OUTPUT_FILE
}
